import cv2 

VIDEO_PATH = "C:/Users/LENOVO/Downloads/Traffic IP Camera video.mp4" #You can replace it 
AREA_THRESHOLD = 2000
MIN_WIDTH = 50
MIN_HEIGHT = 50
KERNEL_SIZE = (5, 5)
LINE_POSITION_Y = 250
DISPLAY_WINDOW_NAME = 'Vehicle Detection'
PREDICTION_COLOR = (255, 0, 0)  # Blue
BOUNDING_BOX_COLOR = (0, 255, 0)  # Green
PREDICTION_RADIUS = 10
BOUNDING_BOX_THICKNESS = 2
FONT = cv2.FONT_HERSHEY_SIMPLEX
FONT_SCALE = 1
FONT_COLOR = (255, 255, 255)  # White
FONT_THICKNESS = 2
